services:

# ------------------------------------------------------------------------------

  server: &server
    build:
      context: ./docker-compose
    volumes:
      - .:/usr/local/src
      - gopath:/go
    working_dir: /usr/local/src
    command:
      - go
      - run
      - main.go
    environment:
      HOSTNAME_CMD: "server"
      HOSTNAME_SERVER_ADDR: "0.0.0.0:50051"

# ------------------------------------------------------------------------------

  client:
    <<: *server
    environment:
      HOSTNAME_CMD: "client"
      HOSTNAME_SERVER_ADDR: "server:50051"
    profiles:
      - donotstart

# ------------------------------------------------------------------------------

volumes:
  gopath:
