services:
  server:
    build:
      context: ./docker-compose
    volumes:
      - .:/usr/local/src
    working_dir: /usr/local/src
    command:
      - go
      - run
      - main.go
    environment:
      HOSTNAME_SERVER_ADDR: "0.0.0.0:50051"
